# Introduction to Tensors in PyTorch

Tensors are the fundamental building blocks in PyTorch, similar to arrays in NumPy but with additional capabilities for GPU acceleration and deep learning. Understanding tensors is essential for anyone working with PyTorch, as they are used to represent data and model parameters in neural networks.

- A torch.Tensor is a multi-dimentional matrix containg elements of a single data type.

- Simiiar to Numpy arrays, but are used to be worked better on GPU's (rather than CPU's).

- Default data type is float32.

- More suitable for deep learning (Neural Networks) than a numpy array.

In [1]:
import torch
import numpy as np

## Comparing Python Lists, NumPy Arrays, and PyTorch Tensors

- **Python Lists**: Flexible, can hold different data types, but not optimized for numerical computations.
- **NumPy Arrays**: Efficient for numerical operations, fixed data type, but mainly CPU-based.
- **PyTorch Tensors**: Similar to NumPy arrays, but support GPU acceleration and are essential for deep learning with PyTorch.

# Lists

In [2]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [4]:
multi_my_list = [[1, 2, 3], [4, 5, 6]]
multi_my_list

[[1, 2, 3], [4, 5, 6]]

# Numpy Arrays

In [5]:
np_array = np.random.rand(3, 3)
np_array

array([[0.57622099, 0.71487346, 0.81373635],
       [0.86330691, 0.47363297, 0.89301039],
       [0.33282158, 0.23899673, 0.2460142 ]])

In [6]:
np_array.dtype

dtype('float64')

# Tensors

In [7]:
tensor_2d = torch.rand(3, 3)
tensor_2d

tensor([[0.2772, 0.7112, 0.7708],
        [0.8292, 0.9373, 0.2262],
        [0.4562, 0.6140, 0.1368]])

In [10]:
tensor_3d = torch.zeros(3, 3, 3)
tensor_3d

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [11]:
## Create tensors from numpy arrays
tensor_from_np = torch.from_numpy(np_array)
tensor_from_np

tensor([[0.5762, 0.7149, 0.8137],
        [0.8633, 0.4736, 0.8930],
        [0.3328, 0.2390, 0.2460]], dtype=torch.float64)

# Summary

- Tensors are the core data structure in PyTorch, enabling efficient computation on both CPUs and GPUs.
- You learned how to create tensors.
- Mastering tensors is essential for building and training neural networks in PyTorch.