# Tensor Operations in PyTorch

This notebook covers essential tensor operations in PyTorch, including reshaping, slicing, and viewing. Mastering these operations is crucial for data preprocessing and building neural networks.

In [1]:
import torch

In [20]:
my_torch = torch.arange(10)
print(my_torch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [5]:
# Reshape the tensor
reshaped_torch = my_torch.reshape(2,5)
print(reshaped_torch)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [6]:
# Reshape the tensor if we don't know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
my_torch2 = my_torch2.reshape(3, -1)
print(my_torch2)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


In [8]:
my_torch3 = torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
my_torch3 = my_torch3.view(3, -1)
print(my_torch3)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


## Summary: `reshape` vs `view`

| Operation | Description | When to Use |
|-----------|-------------|-------------|
| `reshape` | Returns a tensor with a new shape, can handle non-contiguous tensors by copying data if needed | Use when unsure about contiguity or want flexibility |
| `view`    | Returns a tensor with a new shape, but only works on contiguous tensors (no data copy) | Use for efficiency when tensor is contiguous |

> Tip: Use `.is_contiguous()` to check if a tensor is contiguous.

In [10]:
# With reshape and view they will update
my_torch4 = torch.arange(10)
print(my_torch4)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [11]:
my_torch5 = my_torch4.reshape(2, 5)
print(my_torch5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [12]:
my_torch4[1] = 100
print(my_torch4)

tensor([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])


In [13]:
my_torch5

tensor([[  0, 100,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [14]:
# Slices 
my_torch6 = torch.arange(10)
print(my_torch6)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [15]:
# Grab a specific item
my_torch6[7]

tensor(7)

In [16]:
# Grab slice
my_torch7 = my_torch6.reshape(2, 5)
print(my_torch7)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [17]:
my_torch7[:, 1]  # Grab all rows, column 1

tensor([1, 6])

In [18]:
# Return a column
my_torch7[:, 1:]  # Grab all rows from column 1 to the end

tensor([[1, 2, 3, 4],
        [6, 7, 8, 9]])

# Summary

- You learned how to reshape, view, slice, and manipulate tensors in PyTorch.
- Mastering these operations is essential for effective data handling and model building in PyTorch.