# Introduction to Tensor Math Operations

Tensor math operations are fundamental in PyTorch for manipulating data and building neural networks. This notebook covers basic arithmetic, in-place operations, broadcasting, aggregation, and logical operations on tensors.

- Add, Subtract, Multiply, Divide, Remainders, Exponents

- Shorthand and Longhand

- Reassignment

## Shorthand vs Longhand Operations

| Operation      | Shorthand      | Longhand Function      |
|---------------|---------------|-----------------------|
| Addition      | `a + b`       | `torch.add(a, b)`     |
| Subtraction   | `a - b`       | `torch.sub(a, b)`     |
| Multiplication| `a * b`       | `torch.mul(a, b)`     |
| Division      | `a / b`       | `torch.div(a, b)`     |
| Modulus       | `a % b`       | `torch.remainder(a,b)`|
| Power         | `a ** b`      | `torch.pow(a, b)`     |

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1, 2, 3, 4, 5])
tensor_b = torch.tensor([6, 7, 8, 9, 10])

In [3]:
# Addition
tensor_add = tensor_a + tensor_b
print("Addition:", tensor_add)

Addition: tensor([ 7,  9, 11, 13, 15])


In [4]:
# Addition Longhand
tensor_add_long = torch.add(tensor_a, tensor_b)
print("Addition Longhand:", tensor_add_long)

Addition Longhand: tensor([ 7,  9, 11, 13, 15])


In [5]:
# Subtraction
tensor_sub = tensor_a - tensor_b
print("Subtraction:", tensor_sub)

Subtraction: tensor([-5, -5, -5, -5, -5])


In [6]:
# Subtraction Longhand
tensor_sub_long = torch.sub(tensor_a, tensor_b)
print("Subtraction Longhand:", tensor_sub_long)

Subtraction Longhand: tensor([-5, -5, -5, -5, -5])


In [7]:
# Multiplication
tensor_mul = tensor_a * tensor_b
print("Multiplication:", tensor_mul)

Multiplication: tensor([ 6, 14, 24, 36, 50])


In [8]:
# Multiplication Longhand
tensor_mul_long = torch.mul(tensor_a, tensor_b)
print("Multiplication Longhand:", tensor_mul_long)

Multiplication Longhand: tensor([ 6, 14, 24, 36, 50])


In [9]:
# Division
tensor_div = tensor_a / tensor_b
print("Division:", tensor_div)

Division: tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])


In [10]:
# Division Longhand
tensor_div_long = torch.div(tensor_a, tensor_b)
print("Division Longhand:", tensor_div_long)

Division Longhand: tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])


In [11]:
# Remainder Modulus
tensor_mod = tensor_b % tensor_a
print("Remainder Modulus:", tensor_mod)

Remainder Modulus: tensor([0, 1, 2, 1, 0])


In [12]:
# Remaider Modulus Longhand
tensor_mod_long = torch.remainder(tensor_b, tensor_a)
print("Remainder Modulus Longhand:", tensor_mod_long)

Remainder Modulus Longhand: tensor([0, 1, 2, 1, 0])


In [13]:
# Exponentiation / Power
tensor_pow = tensor_a**2
print("Exponentiation / Power:", tensor_pow)

Exponentiation / Power: tensor([ 1,  4,  9, 16, 25])


In [14]:
# Exponentiation / Power Longhand
tensor_pow_long = torch.pow(tensor_a, 2)
print("Exponentiation / Power Longhand:", tensor_pow_long)

Exponentiation / Power Longhand: tensor([ 1,  4,  9, 16, 25])


In [16]:
# Another way to write longhand operations
tensor_a.add(tensor_b)
print("Addition:", tensor_a)

Addition: tensor([1, 2, 3, 4, 5])


## In-place Operations

In-place operations modify the original tensor and are denoted by a trailing underscore (e.g., `add_`). Use with caution, as they can overwrite data and affect computation graphs in autograd.

In [18]:
# Resassigning tensor_a to tensor_b
tensor_a + tensor_b

tensor([ 7,  9, 11, 13, 15])

In [19]:
tensor_a

tensor([1, 2, 3, 4, 5])

In [20]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)
print("In-place Addition:", tensor_a)

In-place Addition: tensor([ 7,  9, 11, 13, 15])


In [21]:
tensor_a

tensor([ 7,  9, 11, 13, 15])

# Summary

- You learned about basic and advanced tensor math operations in PyTorch.
- Covered shorthand/longhand and in-place
- These operations are essential for data manipulation and neural network computations.